// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHDtQrmvzc5TAndKzMRdwWUsdJxBH0nQE',
    appId: '1:452330943156:web:6b231da4305301f8d4dde1',
    messagingSenderId: '452330943156',
    projectId: 'studentproject-a853d',
    authDomain: 'studentproject-a853d.firebaseapp.com',
    storageBucket: 'studentproject-a853d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW0ajvTqckBjetpL1jzTDu_NBsnc8BRuY',
    appId: '1:452330943156:android:1fd0c92eb781c48cd4dde1',
    messagingSenderId: '452330943156',
    projectId: 'studentproject-a853d',
    storageBucket: 'studentproject-a853d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXBmTVx69j3BMaZHB5hgTVjayl4cnVZKs',
    appId: '1:452330943156:ios:9b47c31ab9d98e79d4dde1',
    messagingSenderId: '452330943156',
    projectId: 'studentproject-a853d',
    storageBucket: 'studentproject-a853d.appspot.com',
    iosBundleId: 'com.example.studentProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXBmTVx69j3BMaZHB5hgTVjayl4cnVZKs',
    appId: '1:452330943156:ios:a22fcbaa2b640addd4dde1',
    messagingSenderId: '452330943156',
    projectId: 'studentproject-a853d',
    storageBucket: 'studentproject-a853d.appspot.com',
    iosBundleId: 'com.example.studentProject.RunnerTests',
  );
}
